/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pbpaydtaplcvdwaoexrd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBicGF5ZHRhcGxjdmR3YW9leHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkyNzkwMDgsImV4cCI6MjEwNDg1NTAwOH0.0uyY_-3QFuNEJ2Nu7w6YVD7yL46lv6-7jm5FbvnE03Q"